replicaCount: 1
image:
  repository: ghcr.io/fitnest-backend/identity-service
  tag: "development-289c139"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 8080
  grpcPort: 9090
istio:
  enabled: true
  host: "identity-service"
  mtls:
    mode: STRICT
  authorization:
    internalCallers:
      - "cluster.local/ns/fitnest-dev/sa/user-service"
      - "cluster.local/ns/fitnest-dev/sa/payment-service"
      - "cluster.local/ns/fitnest-dev/sa/catalog-service"
      - "cluster.local/ns/fitnest-dev/sa/order-service"
      - "cluster.local/ns/fitnest-dev/sa/notifications-service"
      - "cluster.local/ns/fitnest-dev/sa/support-service"
      - "cluster.local/ns/fitnest-dev/sa/media-service"
      - "cluster.local/ns/fitnest-dev/sa/fitness-plan-service"
      - "cluster.local/ns/fitnest-dev/sa/api-gateway"
hpa:
  enabled: false
  minReplicas: "1"
  maxReplicas: "3"
  cpuUtilization: "90"
  memoryUtilization: "450Mi"
env:
  JAVA_OPTS: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=65.0 -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xss256k -XX:NativeMemoryTracking=summary"
  JWT_SECRET: your-jwt-secret-change-in-production
  JWT_ISSUER: fitnest
  JWT_ACCESS_TTL_SECONDS: "3600"
  JWT_REFRESH_TTL_SECONDS: "604800"
  SPRING_PROFILES_ACTIVE: dev
  SPRINGDOC_SERVER_URL: "https://dev-api.fitnest.az"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-identity:5432/fitnest_identity?sslmode=disable
  SPRING_DATASOURCE_USERNAME: fitnest_identity
  SPRING_DATASOURCE_PASSWORD: identity_password_123
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_REDIS_HOST: redis
  SPRING_REDIS_PORT: "6379"
  SPRING_REDIS_PASSWORD: ""
  SPRING_REDIS_TIMEOUT: 2000ms
  KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  OTP_TTL_SECONDS: "300"
  OTP_MAX_VERIFY_ATTEMPTS: "3"
  OTP_RESEND_COOLDOWN_SECONDS: "30"
  OTP_RATE_LIMIT_MAX_ATTEMPTS: "5"
  OTP_RATE_LIMIT_WINDOW_MINUTES: "15"
  OTP_RATE_LIMIT_COOLDOWN_SECONDS: "60"
  OTP_RATE_LIMIT_MIN_COOLDOWN_SECONDS: "5"
  OTP_RATE_LIMIT_ERROR_MESSAGE_THRESHOLD_SECONDS: "30"
  LOGGING_LEVEL_ROOT: INFO
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: INFO
  USER_SERVICE_URL: "http://user-service:8080"
resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    cpu: 250m
    memory: 256Mi
