hpa:
  cpuUtilization: '90'
  enabled: false
  maxReplicas: '3'
  memoryUtilization: 600Mi
  minReplicas: '1'
image:
  imagePullSecrets:
    - name: ghcr-secret
  pullPolicy: IfNotPresent
  repository: ghcr.io/fitnest-code/identity-backend
  tag: development-bcfb07f
networkPolicy:
  enabled: true
  extraIngressRules: []
replicaCount: 1
resources:
  limits:
    cpu: 1000m
    memory: 1438Mi
  requests:
    cpu: 20m
    memory: 935Mi
service:
  grpcPort: 9090
  port: 8080
  type: ClusterIP
vaultEnv: development
